PREFIX ontores: <http://ontology.ontotext.com/resource/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT {
	?concept                skos:altLabel   ?altLabel ;
                            skos:prefLabel  ?prefLabel ;
        				    skos:broader    ?immediateBroader .
    ?transitiveBroader      skos:broader    ?broader ;
                            skos:altLabel   ?broaderAltLabel ;
                            skos:prefLabel  ?broaderPrefLabel .
    ?transitiveBroader      skos:broader    ?transitiveBroaderBroader .
} WHERE {
    OPTIONAL { ?concept skos:broader ?immediateBroader .}
    ?concept skos:altLabel ?altLabel ;
                         skos:prefLabel ?prefLabel .
	OPTIONAL { ?concept skos:broader+ ?transitiveBroader .
        BIND(IF(EXISTS{?transitiveBroader skos:broader ?broad}, ?broad, false) AS ?broader) .
    	OPTIONAL { ?transitiveBroader skos:broader ?broad } .
    	OPTIONAL { ?transitiveBroader skos:altLabel ?broaderAltLabel } .
        OPTIONAL { ?transitiveBroader skos:prefLabel ?broaderPrefLabel }
    	OPTIONAL {?transitiveBroader skos:broader ?transitiveBroaderBroader .} } .
     FILTER {{conceptFilter}}
}